const courses = {
    FETCH_COURSES_REQUEST: 'FETCH_COURSES_REQUEST',
    FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
    FETCH_COURSES_FAILED: 'FETCH_COURSES_FAILED',
    SELECTED_COURSE: 'SELECTED_COURSE'
}

export default courses;